apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-docker-jenkins-k8s-demo
  namespace: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node-docker-jenkins-k8s-demo
  template:
    metadata:
      labels:
        app: node-docker-jenkins-k8s-demo
    spec:
      containers:
        - name: app
          image: node-docker-jenkins-k8s-demo:1.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "production"
            - name: APP_VERSION
              value: "1.0"
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"

